server:
  port: 16800
spring:
    profiles:
        active: dev
    application:
      name: trans-gateway
    cloud:
      nacos:
        config:
          file-extension: yaml
          server-addr: 127.0.0.1:8848
        discovery:
          #Nacos的注册地址
          server-addr: 127.0.0.1:8848
      gateway:
        discovery:
          locator:
            enabled: true # 让gateway可以发现nacos中的微服务
        routes:
        - id: auth
          uri: lb://trans-auth
          predicates:
          - Path=/auth/**
          filters:
          - StripPrefix= 1
        - id: system
          uri: lb://trans-system
          predicates:
          - Path=/system/**
          filters:
          - StripPrefix= 1
        - id: app
          uri: lb://trans-app
          predicates:
          - Path=/app/**
          filters:
          - StripPrefix= 1
        - id: open
          uri: lb://trans-open
          predicates:
          - Path=/open/**
          filters:
          - StripPrefix= 1
