server:
  port: 16800
spring:
    profiles:
        active: dev
    application:
      name: trans-gateway
    cloud:
      #Nacos的配置注册
      nacos:
        config:
          file-extension: yml
          server-addr: 127.0.0.1:8848
        discovery:
          server-addr: 127.0.0.1:8848
      #Sentinel熔断限流
      sentinel:
        transport:
          port: 8720
          dashboard: 127.0.0.1:8858
      #Gateway网关路由
      gateway:
        discovery:
          locator:
            enabled: true # 让gateway可以发现nacos中的微服务
        routes:
        - id: trans-system
          uri: lb://trans-system
          predicates:
          - Path=/system/**

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG
